{% set version = '3.2.0' %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-ukbnmr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ukbnmr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ukbnmr/ukbnmr_{{ version }}.tar.gz
  sha256: 01116961d04cfdcf2362941a3759e41df523752af094d0450c6ce1550eb34d2a

build:
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-mass
    - r-bit64
    - r-data.table
    - r-lubridate
  run:
    - r-base
    - r-mass
    - r-bit64
    - r-data.table
    - r-lubridate

test:
  commands:
    - $R -e "library('ukbnmr')"           # [not win]
    - "\"%R%\" -e \"library('ukbnmr')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=ukbnmr
  license: MIT
  summary: A suite of utilities for working with the UK Biobank <https://www.ukbiobank.ac.uk/>
    Nuclear Magnetic Resonance spectroscopy (NMR) metabolomics data <https://biobank.ndph.ox.ac.uk/showcase/label.cgi?id=220>.
    Includes functions for extracting biomarkers from decoded UK Biobank field data,
    removing unwanted technical variation from biomarker concentrations, computing an
    extended set of lipid, fatty acid, and cholesterol fractions, and for re-deriving
    composite biomarkers and ratios after adjusting data for unwanted biological variation.
    For further details on methods see Ritchie SC et al. Sci Data (2023) <doi:10.1038/s41597-023-01949-y>.
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
